
language: groovy

sudo: required

install: true

before_script:
 - ./gradlew -S clean --console=plain

script:
 - ./gradlew -S -i --console=plain build

matrix:
  include:
  - os: linux
    jdk:
    - oraclejdk8
    - oraclejdk7
  - os: osx
    osx_image: xcode8.3jdk

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master
    - development
#    - release
