== Bootstrapping

These plugins are available from the plugin portal. Add the appropriate plugin identifiers to your `build.gradle` file depending on the type of functionality you require.

.build.gradle
[source,groovy,subs="attributes,callouts"]
----
plugins {
  id 'org.ysb33r.nodejs.base'  version '{revnumber}'  // <1>
  id 'org.ysb33r.nodejs.npm'   version '{revnumber}'  // <2>
  id 'org.ysb33r.nodejs.gulp'  version '{revnumber}'  // <3>
}
----
<1> Base plugin
<2> Support for using NPM
<3> Support for using Gulp

NOTE: You need at least Gradle 3.3 to use these plugins.

=== Base plugin

The base plugin provides:

* <<node-defaults,nodejs>> extension.
* <<nodeexec,nodeexec>> execution extension.
* Ability to download and use Node distributions.

=== NPM plugin

The NPM plugin provides:

* <<npm-defaults,npm>> extension.
* <<npmtask,NpmTask>> type.
* `npmexec` project extension to run NPM commands.
* `npm`, `npmDevOnly`, `npmOptional` configurations.
* `npmPackage` for listing packages in Gradle `dependencies` blocks.
* `NpmExecSpec`.

Applying the NPM plugin will apply the base plugin.

=== Gulp plugin

The Gulp plugin provides:

* `gulp` project and task extensions
* `GulpTask` task type.

Applying the Gulp plugin will apply the NPM plugin.
