[[npm-defaults]]
== Configure NPM Defaults

The location of `npm-cli.js` can be supplied in four possible ways:

.build.gradle
[source,groovy]
----
include::{testdir}/NpmExtensionSpec.groovy[tags=configure-with-version,indent=0]

include::{testdir}/NpmExtensionSpec.groovy[tags=configure-with-path,indent=0]

include::{testdir}/NpmExtensionSpec.groovy[tags=configure-with-search-path,indent=0]

include::{testdir}/NpmExtensionSpec.groovy[tags=configure-with-default,indent=0]
----
<1> Supply a version and Gradle will take care of downloading the specific version of `npm` caching it. It will then run the cached version. This is an option for people who want to run a version of `npm` other than the one that ships with Node.js.
<2> Supply a path to the `npm` executable. This works for people that have `npm` installed in predefined locations.
<3> Tell Gradle to look for `npm` (or `npm.cmd`) in the system search path, then infer loation of `npm-cli.js`.
<4> Use the version on `npm-cli.js` that ships with the default version of Node.js. This is also the default operation if nothing is configured.

NOTE: Gradle does not use the `npm` or `npm.cmd` scripts. It uses `npm-cli.js` directly.

The location of the global and local `npmrc` files can also be set.

.build.gradle
[source,groovy]
----
npm {
  localConfig "${projectDir}/npmrc2"
  globalConfig "${project.rootProject.projectDir}/npmrc2"
}
----

NOTE: The default local configuration is always set to an `npmrc` file located in the root of the root project and the global configuration is set to `~/.gradle/npmrc`. This is specifically done so that configuration can be set on a project-wide basis for a Gradle project without interference from a possible globally installed Node.js. Placement of global configuration in the Gradle User Home allows a person to set specific global options for Node projects that are built by Gradle.