[[node-defaults]]
== Configure global Node defaults

The Node.js distribution can be supplied in three possible ways:

.build.gradle
[source,groovy]
----
include::{testdir}/NodeJSExtensionSpec.groovy[tags=configure-with-tag,indent=0]

include::{testdir}/NodeJSExtensionSpec.groovy[tags=configure-with-path,indent=0]

include::{testdir}/NodeJSExtensionSpec.groovy[tags=configure-with-search-path,indent=0]
----
<1> Supply a version and Gradle will take care of downloading the distribution and caching it. It will then used the cached version for running `node`. This is the preferred way of running Node.js with Gradle as it offers better control over reproducible builds.
<2> Supply a path to the `node` executable. This works for people that have Node.js installed in standard locations.
<3> Tell Gradle to look for `node` (or `node.exe`) in the system search path.

If no executable is configured, then Gradle will attempt to download the version specified in link:{api}/org/ysb33r/gradle/nodejs/NodeJSExtension.html#NODEJS_DEFAULT[NodeJSExtension.NODEJS_DEFAULT]. If Gradle runs on a <<platforms,non-supported platform>> this will fail.

[[nodeexec]]
== Using nodeexec

It is possible to run `node` directly from Gradle using the `nodeexec` project execution extension. It operates in a similar fashion to Gradle's link:{gradle-dsl}/org.gradle.api.tasks.Exec.html[Exec] task, but it has it's own `node` nuances, which the user need to setup correctly.

[source,groovy]
----
include::{downloadtestdir}/impl/NodeJSExecutorSpec.groovy[tags=nodeexec-with-closure,indent=0]
----
<1> Specify the name of the script. It can be absolute of relative to the working directory.
<2> Specify any arguments that will be passed to the script.
<3> Set the working directory for the execution. If this is something installed via NPM, then using the location of the NPM homedirectory from the `npm` extension will simplify life.
<4> Specify the locaton of the `node` executable. There are various ways of doig this, but a easy way is to ask the `node` extension to resolve it.

Consult the link:{api}/org/ysb33r/gradle/nodejs/NodeJSExecSpec.html[NodeJSExecSpec API documentation] for full details of all of the settings.